#!/usr/bin/node
const { run, runc } = require("./myutils.js");

// for backup
if (process.argv[2] == "backup") {
  run("cp ~/.vimrc ~/dotfiles/.vimrc");
  run("cp ~/.bashrc ~/dotfiles");
  run("cp -r ~/.config/alacritty ~/dotfiles");
  run("cp -r ~/.i3 ~/dotfiles");
  run("cp -r ~/.vim/snippets ~/dotfiles/.vim");
  run("git add .");
  run("git commit -m 'backup'");
  run("git push -u origin master");
}

// for seting the configuration
if (process.argv[2] == "do") {
  run("cp ~/dotfiles/.bashrc ~/");
  run("cp ~/dotfiles/.vimrc ~/.vimrc");
  run("cp -r ~/dotfiles/alacritty ~/.config");
  run("cp -r ~/dotfiles/.i3 ~");
  run("mkdir ~/.vim/snippets");
  run("cp -r ~/dotfiles/.vim/snippets ~/.vim");
}
