#!/usr/bin/node
const { prun, do_async } = require("./myutils.js");

// for backup
if (process.argv[2] == "backup") {
  do_async(async () => {
    await prun("cp ~/.vimrc ~/dotfiles/.vimrc");
    await prun("cp ~/.bashrc ~/dotfiles");
    await prun("cp ~/.zshrc ~/dotfiles");
    await prun("cp -r ~/.config/alacritty ~/dotfiles");
    //await prun("cp -r ~/.i3 ~/dotfiles");
    await prun("cp -r ~/.vim/snippets ~/dotfiles/.vim");
  });
}

// for seting the configuration
if (process.argv[2] == "do") {
  do_async(async () => {
    await prun("cp ~/dotfiles/.bashrc ~/");
    await prun("cp ~/dotfiles/.zshrc ~/.zshrc");
    await prun("cp ~/dotfiles/.vimrc ~/.vimrc");
    await prun("cp -r ~/dotfiles/alacritty ~/.config");
    //await prun("cp -r ~/dotfiles/.i3 ~");
    prun("mkdir ~/.vim/snippets").catch(() => {});
    await prun("cp -r ~/dotfiles/.vim/snippets ~/.vim");
  });
}
