#!/usr/bin/node
const { exec } = require("child_process");

// for backup
if (process.argv[2] == "backup") {
  exec("cp ~/.vimrc ~/dotfiles/.vimrc", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".vimrc -->" + sout);
  });

  exec("cp -r ~/.config/termite ~/dotfiles", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".vimrc -->" + sout);
  });

  exec("cp -r ~/.i3 ~/dotfiles", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".i3 -->" + sout);
  });

  exec("cp -r ~/.vim/snippets ~/dotfiles/.vim", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".vim/sinppets -->" + sout);
  });

  exec("git add .", (err, sout, serr) => {
    handleErr(err, serr);
    console.log("git add . -->" + sout);
  });

  exec("git commit -m 'backup'", (err, sout, serr) => {
    handleErr(err, serr);
    console.log("git commit -->" + sout);
  });

  exec("git push -u origin master", (err, sout, serr) => {
    handleErr(err, serr);
    console.log("git push -->" + sout);
  });
}

// for seting the configuration
if (process.argv[2] == "do") {
  exec("cp ~/dotfiles/.vimrc ~/.vimrc", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".vimrc <--" + sout);
  });

  exec("cp -r ~/dotfiles/termite ~/.config", (err, sout, serr) => {
    handleErr(err, serr);
    console.log("termite <--" + sout);
  });

  exec("cp -r ~/dotfiles/.i3 ~", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".i3 <--" + sout);
  });

  exec("mkdir ~/.vim/snippets", (err, sout, serr) => {
    handleErr(err, serr);
    console.log("created .vim/sinppets <---" + sout);
  });

  exec("cp -r ~/dotfiles/.vim/snippets ~/.vim", (err, sout, serr) => {
    handleErr(err, serr);
    console.log(".vim/sinppets <---" + sout);
  });
}

function handleErr(err, serr) {
  if (err) console.log("Err : " + err);
  if (serr) console.log("Serr: " + serr);
}
