#!/usr/bin/node

const { run, runc } = require("./myutils");
let ran = false;

// deleting all the containers
if (process.argv[2] == "dc") {
  ran = true;
  runc('docker ps -a --format "{{.ID}}"', (sout) => {
    if (sout) {
      const containers = sout.split("\n").filter((val) => val.length > 4);
      for (let cont of containers) {
        console.log("Deleting container with ID:" + cont);
        run("docker rm -f " + cont);
      }
    }
  });
}

// deleting useless images
if (process.argv[2] == "di") {
  ran = true;
  runc('docker images --format "{{.Tag}}|{{.ID}}"', (out) => {
    out
      .split("\n")
      .filter((val) => !val.includes("alpine"))
      .filter((val) => val.length > 2)
      .map((val) => val.split("|"))
      .forEach((val) => {
        run("docker image rm -f " + val[1]);
      });
  });
}

// pulling usual images
if (process.argv[2] == "pi") {
  ran = true;
  run("docker pull node:14-alpine");
  run("docker pull postgres:alpine");
  run("docker pull nginx:alpine");
  run("docker pull redis:alpine");
}

// deleting all the volumes
if (process.argv[2] == "dv") {
  ran = true;
  runc(`docker volume list --format {{.Name}}`, (res) => {
    res
      .split("\n")
      .filter((val) => val.length > 5)
      .forEach((val) => run(`docker volume rm ${val}`));
  });
}

ran ? null : console.log("Invalid Operation!");
